### ISSUE TITLE
replace lightbox with plain js in new activejobs

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1032]
Lightbox was dropped during the merging of activejobs into the dashboard. This ticket is to have a functional replacement with it in plain old javascript.

Something like this should work.

```javascript
$('#directory-contents tbody').on('click', '.view-file', function(e){
  e.preventDefault();
  let row = table.row(this.dataset.rowIndex).data();
  window.open(row.url, 'ViewFile', "location=yes,resizable=yes,scrollbars=yes,status=yes");
});
```

Ganglia extended panels use this feature.  You can use this config to use Berkeley's public ganglia instance.

```yaml
    ganglia:
      host: "tiger.cchem.berkeley.edu/ganglia"
      scheme: "http://"
      segments:
        - "graph.php"
      req_query:
        c: "Pitzer"
      opt_query:
        h: "%{h}.ten.osc.edu"
      version: "3
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823051571629) by [Unito](https://www.unito.io)
