### ISSUE TITLE
Add poll interval for custom widgets

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#1098]
Two changes here

1. instead of a "string" for a widget, a yaml map could be used (which becomes Ruby hash) in the config for 
1. if `poll: X_secs` specified as an option in this map, then the widget will include JS to fetch an updated version of the erb every X seconds. For example:

```
layout:
  rows:
    - columns:
         - widgets: { name: 'motd', poll: 60 }
           width: 8
```

* Every 60 seconds the motd will update.
* without poll present, no polling is done (reloaded on each request)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823005553528) by [Unito](https://www.unito.io)
