### ISSUE TITLE
Use scrollspy to fix the expanded row at top when it scrolls out of view

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#133]
When I expand a row and then scroll down, I lose the context of the job:

![screen shot 2016-06-03 at 1 02 20 pm](https://cloud.githubusercontent.com/assets/512333/15786772/6d0f97da-298c-11e6-8547-6c5fb8c73d3e.png)

![screen shot 2016-06-03 at 1 02 24 pm](https://cloud.githubusercontent.com/assets/512333/15786732/3a7b723a-298c-11e6-9e72-a62987bd456d.png)

We can use scrollspy to temporarily apply a "currently-viewing" class to when we scroll past the row so its out of view - this way the information in that row could be displayed:

![screen shot 2016-06-03 at 1 02 24 pm copy](https://cloud.githubusercontent.com/assets/512333/15786866/e604e320-298c-11e6-9de4-ab37380b7c55.png)

You can do this if the "currently-viewing" class applies "position fixed" to the row, but determining the correct style modifications after you do that will take a little bit of time. This screenshot shows a quick example where I pop the row contents out, but it doesn't look ideal:

![screen shot 2016-06-03 at 1 06 35 pm](https://cloud.githubusercontent.com/assets/512333/15786913/18a3fbcc-298d-11e6-911d-99c3231e8124.png)

Though even this might be good enough. The styles I used to apply to this would be:

``` css

.currently-viewing {
    position: fixed;
    top: 0;
    z-index: 2000;
    background-color: white;
    border: 1px solid #ddd;

    /* round corner and add dropshadow */
    -webkit-box-shadow: 1px 1px 5px 0px rgba(0,0,0,0.75);
    -moz-box-shadow: 1px 1px 5px 0px rgba(0,0,0,0.75);
    box-shadow: 1px 1px 5px 0px rgba(0,0,0,0.75);
    -webkit-border-radius: 5px;
    -moz-border-radius: 5px;
    border-radius: 5px;
}
```
