### ISSUE TITLE
Dynamic content in the form.yml.erb for apps

### ISSUE THREAD

**Issue by Micket** [OSC/ondemand#1401]
On the server side we typically know things that users enter into apps like the `bc_desktop`, for example the slurm accounts that happens to be available for a given user.
Is it possible to feed the template code such custom information so that we could e.g.
```
attributes:
  bc_account:
    widget: "select"
    options:
      <%- slurm_accounts.each do |acc| %>
      - "<%= acc %>"
      <%- end %>
```
I was hoping to do something like this, not just for the slurm accounts but also some center specific modifications based on the available software versions, project directories, etc. 
Perhaps it's already possible to have such a server side hook to add extra content to the template?
