### ISSUE TITLE
automatic js handlers for min & max

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1431]
Breaking up #851, let's add handlers to modify the min and max settings on another form attribute.

This is an example config similar to what we have on pitzer. With this feature - the cores form item would have a max value reset based off of which node type is currently selected.

```yaml
form:
  - cores
  - node_type
attributes:
  node_type:
    widget: select
    options:
    -  [
          '40core',
          data-max-cores: 40,
       ] 
    -  [
          '48core',
          data-max-cores: 48,
       ]
  cores:
    widget: 'number_field'
    max: 28
```
