### ISSUE TITLE
automatic js handlers for hidden form items

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1432]
Continuing to break up #851, let's add handlers for hiding and showing entire form items. The use case the comes to mind is we want to hide the CUDA version form item for any node type other than GPUs

Given a configuration like this - we'd hide the `cuda_version` form item when regular `node_type` is chosen.
```yaml
form:
  - cuda_version
  - node_type
attributes:
  node_type:
    widget: select
    options:
    -  [
          'gpu',
       ] 
    -  [
          'regular',
          data-hide-cuda-version: true,
       ]
  cuda_version:
    widget: 'select'
    options:
      -  1.123
      -  2.456
```
