### ISSUE TITLE
min/max handlers account for last setting

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1446]
Let's say we have 2 node types configured below.

```yaml
      - [
          'any',
          data-max-num-cores-for-cluster-owens: 40,
         ]
      - [
          "hugemem", "hugemem",
          data-min-num-cores-for-cluster-owens: 48,
          data-max-num-cores-for-cluster-owens: 48,
        ]
```

Now when I toggle between the 2, the max is correctly being set.  Let's say the min get's initialized to 1. As soon as I choose `hugemem`, it's set to 48. But when I toggle back to `any` the minimum persists.  Users would have to explicitly set min _and_ max values all over the place, when most of the time they only want to set the max.

So it seems like in this case, when going from `hugemem` to `any` we'd have to set the min to some default value like maybe 1 or whatever the form started with, before we handled any changes.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737389289387) by [Unito](https://www.unito.io)
