### ISSUE TITLE
js to auto populate values

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1447]
Let's take this use case where I want to auto populate a field based off of a select widget's value.

```yaml
form:
  - classroom
  - account
attributes:
  classroom:
    widget: 'select'
     -  [
          'Physics 1234',
          data-set-account: "phy1234",
        ]
     -  [
          'Math 4567',
          data-set-account: "mat4567",
        ]
   account: "changeme"
```

Here when I choose classroom `Physics 1234` I want to auto populate the account field with `phy1234`. With this feature and configuration, customers won't have to care about the account field, only the classroom field. The jobs will be submitted with the right chargeback code automatically.
