### ISSUE TITLE
Help with grafana MyJobs integration

### ISSUE THREAD

**Issue by sjpb** [OSC/ondemand#1511]
Hope it's ok to raise an issue for help with this.

I've got a cluster which already had a working grafana, on the slurmctld node.

I've tried to add the grafana integration into the Active Jobs app, but although the app shows a job OK, the two monitoring panes are just blank. Having looked in `/var/log/ondemand-nginx/<user>/error.log`, if I go to `https://<myondemandserver_ip>/pun/sys/dashboard/activejobs/json` I see:

```
{"name":null,"error":"Request did not specify an available cluster. Available clusters are: slurm But specified cluster is: "}
```

in the above `error.log` I can see the command it's running for info is `squeue ... -M alaska` which looks ok, i.e. that is the correct cluster name.

I'm using the `osc.ood` ansible role to configure this, and my `clusters` role var looks like this, where `openhpc_cluster_name: alaska`:

```yaml
openondemand_clusters:
  slurm:
    v2:
      metadata:
        title: alaska
      login:
        host: "<my.login.ip>"
        default: true
      job:
        adapter: slurm
        cluster: alaska
      <snip>
      custom:
        grafana:
          host: "http://{{ grafana_hostname }}:3000"
          orgId: 1
          dashboard:
            name: "node-exporter-slurm"
            uid: "node-exporter-slurm"
            panels:
              cpu: 77
              memory: 78
          labels:
            cluster: "cluster"
            host: "host"
            jobid: "jobid"
          cluster_override: slurm
```

I'm a bit confused by which way around cluster_override should be but I've tried both `slurm` and `alaska` - omitting it is definitely bad.

Interestingly the "Detailed metrics" links job app page are correct (well, I'm having to proxy in so I have to replace the hostname with localhost but that's expected).

Any help greatly appreciated, this looks like a really nice feature.
