### ISSUE TITLE
Per cluster data-root doesn't sanatize cluster

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1601]
I accidentally made this `per-cluster dataroot` which is obviously wrong.
```
data/batch_connect/["kubernetes", "kubernetes-test", "kubernetes-dev"]/usr/johrstrom/classroom-jupyter
```
Here's the config to replicate. It's when you define the cluster in the form, and it's actually misconfigured to be a static array (should actually be a select widget with those options).

```yaml
form:
- cluster
attributes:
  cluster:
     - 'kubernetes'
     - 'kubernetes-test'
     - 'kubernetes-dev'
```
