### ISSUE TITLE
batch connect forms use cluster prettty name

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1648]
Users, like this discourse topic, https://discourse.osc.edu/t/form-yml-submit-yml-erb-and-documentation/1828/4 may want to see a more human friendly name like `Amarel Cluster` instead of just `amaral`.

```yaml
# /etc/ood/config/clusters.d/amarel.yml
v2:
  metadata:
    title: Amarel Cluster
```

 I think in the least, we can titleize the name. At best, we could read the title from the file and us that instead.
