### ISSUE TITLE
help menu respond to array

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1909]
Our help menu is built off of 4 or 5 environment variables.

Instead, it should respond to this configuration in an `ondemand.d` file.

```yaml
help_menu:
  -  url: example.com/help
     icon: question-circle
  - url: other
    icon: exclamation-circle
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823705301549) by [Unito](https://www.unito.io)
