### ISSUE TITLE
Caching SLURM account information for use in app forms

### ISSUE THREAD

**Issue by Micket** [OSC/ondemand#1970]
Feature request:
I currently have a dashboard initializer `apps/dashboard/initializers/ood.rb`  which does;

```ruby
class SlurmData
  def self.accounts
    username = Etc.getlogin
    accounts = []
    IO.popen 'sacctmgr -np show accounts withassoc format=account,user' do |io|
      io.each do |line|
        acc = line.split('|')
        if acc[1] == username
          accounts.append(acc[0])
        end
      end
    end
    return accounts
  end
end
```

(which could of course be cleaned up (I think it should have used CurrentUser?), extended to fetch partitions, reservations, clusters. but I have not yet had any such need).

It lets me switch away from free text field as input and instead conveniently configure my apps to just do;

```yml
  bc_account:
    widget: "select"
    options: [<%= SlurmData.accounts.join(', ') %>]
    ...
```

which conveniently only presents the user with valid options; and for most users there is just one option which gets auto-selected.

In fact, this seems so generally applicable, I can't think of a reason why you wouldn't always want to do it like this, having all of this just be the default behavior.
Extending it to a multi cluster setup also seems feasible.

Is there any broader interest in this? I can work on a PR if there is (though my ruby is weak)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823757987957) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Yes I think we'd want this. We're adding `auto_primary_group` right now in #1964. so this may be `auto_accounts`?

That said, I don't think we'd want to use `sacctmgr` or if we did we'd have to push it to https://github.com/OSC/ood_core where all our cross scheduler logic is.

My guess is a simple group filter would do the trick. For us at OSC it'd be `^P*`.  All our chargeback projects start with a P like PZS0714.  A group filter like `^P*` at OSC would filter out all the other entitlement groups I'm also in like `oscstaff`.  Would such a group filter work for you as well?

**Comment by johrstrom** [comment]
> you would still not have partitions, QoS, reservations available

These would be separate fields.  `auto_queues` would come have to come from ood_core, but i don't know about QoS or reservations. I'll have to check if those are cross scheduler fields and how that may fit. I've also got #1763 for things that are more static (of QoS is generally static).

> Is there an issue pushing it to core?

No, not at all if it fits there.

> this would basically render auto_primary_group unnecessary.

This a choice you're presenting to the user.  `auto_primary_group` doesn't even show up in the form as an option. So the behavior of submitting the job with the primary group as the accounting_id is transparent to the user.

**Comment by Micket** [comment]
My goal here is to be able to stay as close to upstream as possible (since maintaining a fork is painful), so my hope is to find something pretty much everyone could be happy with to eliminate the need for forking off code.

I have a few question marks/design decisions;

1. Would we keep some "queue accounting information"-struct, similarly to e.g. `OodFilesApp`, to be some globally accessible variable which could be used for all sort of things (perhaps some additional site-specific logic inside a `submit.yml.erb` file)? 
And also having these smart attributes as an additional feature on top of that?

2. Slurm basically has fairshares on each  `(cluster,account,partition,qos)`-tuple; meaning there may (perhaps even likely) that not all combinations exists; perhaps most commonly, a project might not have access to some particular partition.
Similarly to how a node configurations isn't necessarily available for a given cluster (or partition).

I suppose the main 2 options for problem 2  would be;
a. Flatten it; just list all the possible options independently with the expectation that the user should know what combination of partition and account they can choose.

b. Keep track of what combinations exist. Not at all difficult in the code;  basically just a hierarchy e.g.
```yml
{
    'cluster_a': {
        'account_a': ['partition_a', 'partition_b']
        'account_b': ['partition_a']
    }
    'cluster_b': {
        'account_c': ['partition_c']
    }
}
```
I've seen there is `data-option-for-cluster-xxx` tags (https://github.com/OSC/bc_osc_jupyter/blob/master/form.yml.erb#L63)  Could this be extended here? (I only have 1 cluster, so, i haven't really been able to test this at all).
The struct above would be ideally boil down to something like
```yml
attributes:
  account:
    widget: "select"
    options:
      - [ "account_a", data-option-for-cluster-cluster_a: true ]
      - [ "account_b", data-option-for-cluster-cluster_a: true ]
      - [ "account_c", data-option-for-cluster-cluster_b: true ]
  partition:
    widget: "select"
    options:
      - [ "partition_a", data-options-for-account-account_a: true, data-options-for-account-account_b: true ]
      - [ "partition_b", data-options-for-account-account_a: true ]
      - [ "partition_c", data-options-for-account-account_c: true ]
```
If other schedulers actually don't have this split of project allocations per partition, then, one could still just populate the struct completely. 

QoS is probably overkill (I don't want to present it), but I see no reason why it couldn't be done generally like this.
