### ISSUE TITLE
batch connect confirmation dialogue

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2033]
https://discourse.openondemand.org/t/add-confirmation-step-to-launch-interactive-apps/2077

From discourse - the basic idea is to prompt the user with an 'are you sure?' dialogue with their current allocation request. I'd say we could add a flag in the form for this behavior.

```yaml

prompt: true

# or override the message from 'are you sure?'
prompt:
   message: "Do you need a custom message?"

```
