### ISSUE TITLE
Support for configuration profile aliases 

### ISSUE THREAD

**Issue by adaybujeda** [OSC/ondemand#2214]
Part of the work related to user profiles: #2126 

Add support to define multiple names for a profile. Similar to how `ServerAlias` work in Apache named virtual hosts.

This will be useful for hostname based profiles, it is common for multiple hostnames to identify the same site. This will avoid the need to copy the same profile with different names to server all hostnames.

relates to #1568 

Example configuration with `alias`:

```yaml
profiles:
  ondemand:
    alias: ["ondemand.osc.edu", "ondemand2.osc.edu"]
  classroom:
    alias: ["class.osc.edu"] 
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202728619378688) by [Unito](https://www.unito.io)

**Comment by adaybujeda** [comment]
The aliases are not specific to hostnames. They are generic and provide multiple names for the same profile

**Comment by johrstrom** [comment]
Yea I was kind of thinking we'd rely on YAML facilities for the same. So you could have a base profile - but then override things.

```yaml
  ondemand_base: &ondemand_base
    # ... 
  ondemand.osc.edu: 
    <<: *ondemand_base
    one_single_override: 'some other value'
```
