### ISSUE TITLE
Configuration based navigation links

### ISSUE THREAD

**Issue by adaybujeda** [OSC/ondemand#2244]
Add support to add custom links to the left hand side navigation using the configuration files and profiles.

Features:

* Support for category and subcategory.
* Support for icons
* support for system apps using tokens.

Configuration idea:

```yaml
nav_links:
  - category: "Custom Menu"
    title: "Help"
    icon: fa://desktop
    url: "/help"
    new_tab: false
  - category: "Sid"
    subcategory: "Custom Menu"
    title: "Documentation"
    url: "/docs"
    new_tab: true
  - category: "Jobs"
    subcategory: "Shell in Jobs"
    token: "sys/shell"
```

Relates to redesigning how we add links to the navbar: https://github.com/OSC/ondemand/issues/2154

Part of the work related to user profiles: https://github.com/OSC/ondemand/issues/2126

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202822754796346) by [Unito](https://www.unito.io)
