### ISSUE TITLE
navbar configuration groups & titles

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2271]
Thanks, I think this is ready. One thing that I'm going to make a ticket on now is how the config uses `group` to create sub-categories & dividers. Maybe that should be `title`? 

I can't tell, but there's something that's not intuitive about this. I just mean there may be some slight tweak here that'll make it easier to document and understand.

Take this as an example. Here we're using `group` and `title` both as separators. Sometimes within the navigation item and sometimes outside of it.

```yaml
nav_bar
 - title: "Apps Menu"
   links:
     - "sys/bc_osc_rstudio/*"
     - apps: [ "sys/bc_osc_jupyter" ]
     - group: "SubApp"
       apps: [ "sys/bc_desktop" ]
     - group: "Core Apps"
     - apps: [ "sys/bc_desktop" ]
     - group: "RStudio"
     - apps: [ "sys/bc_osc_rstudio/*" ]
     - group: "Profiles"
     - title: "Team 1"
       profile: "team1"
     - title: "Team 2"
       profile: "team2"
```

_Originally posted by johrstrom in https://github.com/OSC/ondemand/pull/2270#pullrequestreview-1099712332_

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1203792863438278) by [Unito](https://www.unito.io)
