### ISSUE TITLE
Add support for full definition of the right hand side navigation

### ISSUE THREAD

**Issue by adaybujeda** [OSC/ondemand#2276]
Based on the work done for https://github.com/OSC/ondemand/issues/2154, we would like to do the same for the right hand side navigation.

To be able to configure the navigation items on the right hand side navigation using the UserConfiguration object

**Comment by adaybujeda** [comment]
We could define a new property called `help_bar`. If defined, the new right hand side navigation will be rendered.

By adding 2 new static links to support `Logged in as <user>`, and `Log Out`, we should be able to support all right hand side navigation use cases

**Comment by adaybujeda** [comment]
Proposal:

```yaml
    help_bar:
      - title: "Help"
        links:
          - group: "Doc Links"
          - apps: "sys/sas"
          - group: "Other Links"
          - apps: "sys/sas"
          - title: "how to docs"
            icon_uri: fa://desktop
            url: "/docs"
            new_tab: true
          - title: "submit a help ticket"
            icon_uri: fa://question-circle
            url: "/tickets"
            new_tab: false
          - apps: "sys/sas"
      - "user"
      - "log_out"
```

<img width="814" alt="Screenshot 2022-09-09 at 16 32 32" src="https://user-images.githubusercontent.com/17336210/189387431-86daa516-73a3-42b0-8479-67e3ddbaca12.png">
