### ISSUE TITLE
OnDemand UI - Custom Pages - Add new pages with layouts and widgets based on configuration

### ISSUE THREAD

**Issue by adaybujeda** [OSC/ondemand#2322]
# Story Description
Feature to add new pages on the OnDemand UI. These pages can be filled with content based on layouts and widgets.
The pages will be configured using config files and the `UserConfiguration` object.

Each page is identified by a `page_code`. This `page_code` will be part of the URL and used as a lookup key to find the configuration for the page.

This is part of the work for user profiles: https://github.com/OSC/ondemand/issues/2126

# Definition of Done
Create new controller, that responds to GET request to the URL: ` /custom/:page_code`
`page_code` is the page identifier. This identifier will be used to lookup the page layout.

New `UserConfiguration` item will be added with page configurations, eg:
This is a configuration for the 2 new pages: `help` and `docs`.
The configuration layout is the same as per `dashboard_layout` property.
```yaml
custom_pages:
  help:
    rows:
      - columns:
          - width: 12
            widgets:
              - "help_widget"
  docs:
    rows:
      - columns:
          - width: 12
            widgets:
              - "docs_widget"
```
Valid URLs for this configuration:
- ` /custom/help`
- ` /custom/docs`

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203135174600706) by [Unito](https://www.unito.io)
