### ISSUE TITLE
Customize Left Hand applications navigation for Interactive Apps and My Interactive Sessions

### ISSUE THREAD

**Issue by adaybujeda** [OSC/ondemand#2326]
# Story Description
Add support to configure the list of applications/links that appear in the left hand menu on the `Interactive Apps` and `My Interactive Sessions` page.

Now that we can fully customize the Main navigation, the `Interactive Apps` navigation item might be custom or not defined.
To have control of what appears in the left hand side menu, we should support its customization.

This is a requirement for the IQSS Sid project.

Relates to #2223 

Part of the work related to user profiles: https://github.com/OSC/ondemand/issues/2126

## Technical Notes
The default behaviour when a custom navigation is defined is to scan all the applications that have been used to configure the navigation and use these apps to render the new left hand side navigation.
There is a new menu title:` t('dashboard.batch_connect_apps_menu_title')`
The apps will be sorted and arranged as per their custom navigation subcategories defined in the new navigation.

This behaviour can be overridden with a new custom UserConfiguration property to fully define the items in this navigation.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203149572295355) by [Unito](https://www.unito.io)

**Comment by adaybujeda** [comment]
This is an screenshot of the menu:

<img width="1414" alt="Screenshot 2022-10-11 at 12 16 04" src="https://user-images.githubusercontent.com/17336210/195316614-27af31f7-56b9-47c4-b007-ca41c14ac025.png">

**Comment by adaybujeda** [comment]
We are working on a prototype that uses the current `NavBar` functionality to create this navigation using a new `UserConfiguration` property:

```yaml
    apps_menu:
      - title: "Inter Apps"
        links:
          - group: "Doc Links"
          - apps: "sys/sas"
          - group: "Other Links"
          - apps: "sys/sas"
          - title: "how to docs"
            description: "This is how we do it"
            icon_uri: fa://desktop
            url: "/docs"
            new_tab: true
          - title: "submit a help ticket"
            icon_uri: fa://question-circle
            url: "/tickets"
            new_tab: false
          - apps: "sys/Rstudio/*"
```
