### ISSUE TITLE
Custom Navigation - Configuration Improvements

### ISSUE THREAD

**Issue by adaybujeda** [OSC/ondemand#2336]
There are certain edge cases for the custom navigation implementation that should be reviewed/updated.

1 .- String top level items. It should configure only 1 application or 1 category. eg:

```yaml
    nav_bar:
      - "sys/shell"
      - "interactive apps"
```

When the string matches more than one application, the result should be discarded/ignored. This is because applications cannot be grouped under a single menu item. Matched applications have multiple categories that is not possible to consolidate effectively. the current logic will select the first group/category that matches and discard the rest.
eg:

```yaml
    nav_bar:
      - "sys/*"
```

2 .- Add support for top level item for multiple apps. eg:

```yaml
    nav_bar:
      - title: "My Applications"
        apps: "sys/*"
```

In the example above, the application subcategories from `"sys/*"` will be used to group the applications within the `"My Applications"` menu.
When title is missing, ~~a default title will be used or~~ the entry will be discarded.

3 .- Add support for existing Dashboard urls like, the sessions, support, all_apps, restart server, ... This is to allow users to create custom links to these pages without having to hard-code the dashboard page URL.
```yaml
    nav_bar:
      - title: "Support"
        icon_uri: fa://desktop
        url: "support_ticket"
```
In this example, the URL for this link will be overridden with the path to the `support_ticket` page.

4 .- Add support for icons to top level menu items.

```yaml
    nav_bar:
      - title: "Help"
        icon_uri: fa://question-circle
        links: []
```

Relates to https://github.com/OSC/ondemand/issues/2126
Relates to https://github.com/OSC/ondemand/issues/2154 

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203226720190505) by [Unito](https://www.unito.io)
