### ISSUE TITLE
Pinned Apps - Tile content improvements

### ISSUE THREAD

**Issue by adaybujeda** [OSC/ondemand#2345]
# Issue Description
The amount of information that can be displayed in a pinned app tile is very limited.

With the use of `preset` apps, it would be more useful to users to display more information about the app or configuration used.

## Proposal
Add customizable content to the pinned app tile to allow administrators to add more information into the tile.
Proposed customizable items just for the pinned app tile, these will not affect navigation:

```yaml
pinned_apps:
  - token: sys/Rstudio/regular
    view:
      title: "RStudio application"
      icon_uri: fa://desktop
      color: "#DA6027"
      sub_title: |
         1 CPU core and 16GB RAM
         4 hours job run time
         Dev cluster
```

This is an screenshot of the proposal:

<img src="https://user-images.githubusercontent.com/17336210/198567877-86bd9232-087b-49b6-ace7-2a6a222131a7.png" width="300">

<img width="580" alt="Screenshot 2022-10-31 at 19 50 07" src="https://user-images.githubusercontent.com/17336210/199097806-39fb2346-7107-49ba-997a-6ccf62c84199.png">

Relates to https://github.com/OSC/ondemand/issues/2126

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203258634012173) by [Unito](https://www.unito.io)

**Comment by adaybujeda** [comment]
For the configuration, I am currently using 2 places. For batch connect apps, I have added a new metadata configuration item in the `form.yml` file with a pinned_app section. This is applicable to subapp forms:

```yaml
metadata:
  show_in_nav: false
  pinned_app:
    title: "Run RStudio"
    icon_uri: fa://desktop
    p1: "1 CPU core and 8GB RAM"
    p2: "8 hours job run time"
    p3: "Dev cluster"
```

As well, we can define the same in the pinned_apps configuration, eg:
```yaml
pinned_apps:
  - token: sys/Rstudio/regular
    title: "RStudio application"
    p1: "1 CPU core and 8GB RAM"
    p2: "16 hours job run time"
    p3: "Dev Cluster"
  - token: sys/shell
    title: "Shell application"
    p1: "1 CPU core and 8GB RAM"
    p2: "16 hours job run time"
    p3: "Dev Cluster"
```
This is backwards compatible with existing configurations

**Comment by johrstrom** [comment]
Without seeing the code - I will say that the whole p1-p3 doesn't look so nice. Can it be 1 thing like `sub_caption` that we can split on newlines?  (yaml allows for multi line)

```yaml
  sub_caption: |
    this should be
    more than one
    line
```

```ruby
<%- sub_caption.split.each do |line| -%>
   <p><%= line %></p>
<%- end -%>
```

**Comment by adaybujeda** [comment]
Looks nice!. Let me have a play.

**Comment by adaybujeda** [comment]
Works really nicely. I have updated the comments above to reflect the change: using a single item with multiple lines

**Comment by adaybujeda** [comment]
Created PR with the changes: https://github.com/OSC/ondemand/pull/2351

**Comment by adaybujeda** [comment]
To create multiple preset configurations for the same app without affecting the navigation, I have added a new property to the application form metadata called `show_in_nav`. Apps/sub apps with this field set to true can be used as pinned apps and will not show in the navigation.

**Comment by adaybujeda** [comment]
After careful consideration and trying different implementations, I think that the configuration for the view items for pinned apps should only be in the `pinned_apps` configuration list.

I have updated the references to do the same in the form file for batch connect apps.

Summary: Enhanced view for pinned apps can only be configure with extra fields in the `pinned_apps` config item:

```yaml
pinned_apps:
  - token: sys/Rstudio/regular
    view:
      icon_uri: fa://desktop
      title: "RStudio application"
      sub_title: |
         1 CPU core and 16GB RAM
         4 hours job run time
         Dev cluster
  - token: sys/shell
    view:
      title: "Shell application"
      sub_title: |
         2 CPU core and 8GB RAM
         16 hours job run time
```
         Dev cluster
