### ISSUE TITLE
clamping to or from 0 seems broken

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2362]
We have this for the ascend cluster and given the steps below 

```yaml
form:
  - gpus
  - node_type
attributes:
  gpus:
    widget: number_field
    value: 0
    min: 0
    max: 4
  node_type:
    widget: select
    label: "Node type"
    help: |
      Need docs
    options:
      - [ 
          "cpu", "any",
          data-min-num-cores: 1,
          data-min-gpus: 0,
          data-max-gpus: 0,
          data-max-num-cores: 84,
          data-hide-gpus: true,
        ]
      - [ 
          "gpu", "gpu-any",
          data-min-gpus: 1,
          data-max-gpus: 4,
          data-min-num-cores: 1,
          data-max-num-cores: 88,
        ]
```

steps to reproduce:
* set the node_type to gpus
* set gpus to 0
* select node type cpu
* select node type gpu
* [bug] see that gpus is now set to 4 when it should have been set to 0.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203325968198874) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1202821104799596/1203325968198874
