### ISSUE TITLE
data-hide doesn't hide on first page load

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2409]
Similar to #1650 (dealing with mins and maxes) - `data-hide` directive don't work on initialization when there are multiple of them.

Here's a `form.yml` to replicate.  The expectation is that `cuda_version` is hidden on page load because `node_type` is set to `any`. 
```yaml

---
title: "Test Stuff"
cluster:
  - "owens"
  - "pitzer"
description: |
  This is a test jupyter app.

form:
  - node_type
  - cuda_version
  - conflicting_hide
attributes:
  cuda_version:
    widget: select
    options:
      - "9"
      - "10"
      - "11"
      - "12"
  node_type:
    widget: select
    options:
      - [ "any", "any", data-hide-cuda-version: true ]
      - [ "gpu", "gpu"]
  conflicting_hide:
    widget: select
    options:
      - [ "conflict", "conflict", ]
      
       # this is the causing the bug. Initializing this handler will do something to the effect of 
       # conflicting_hide needs a handler to hide cuda_version
       # conflicting_hide is currently set to 'conflict' which will show cuda_version
       # so show cuda_version (even though the any node_type setting above this should have hidden it)
      - [ "safe", "safe", data-hide-cuda-version: true]
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203503306362667) by [Unito](https://www.unito.io)
