### ISSUE TITLE
data-[min,max] on 2 fields doesn't work correctly

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2410]
Setting mins and maxes on 2 different fields doesn't work as expected. 

The form that replicates this issue is below in details. Load that form and:

* select pitzer cluster and see `additional_constraints` form field
* select `40 core` from `additional_constraints`
* `num_cores` should be clamped to 40 at this point. However, it is still 48.  This is the bug. Changing `node_type` works as expected, but when I change `additional_constraints` it does not set new mins & maxes.

<details>

```yaml
---
title: "Test Stuff"

description: |
  This is a test jupyter app.

form:
  - cluster
  - node_type
  - additional_constraints
  - num_cores
attributes:
  cluster:
    widget: select
    options:
      - [ "owens", "owens", data-hide-additional-constraints: true ]
      - [ "pitzer", "pitzer" ]
  num_cores:
    widget: number_field
    min: 1
    max: 28
    value: 28
  node_type:
    widget: select
    options:
      - [ 
          "any", "any", 
          data-min-num-cores-for-cluster-pitzer: 1,
          data-max-num-cores-for-cluster-pitzer: 48,
          data-min-num-cores-for-cluster-owens: 1,
          data-max-num-cores-for-cluster-owens: 28,
        ]
      - [ 
          "gpu", "gpu",
          data-min-num-cores-for-cluster-pitzer: 1,
          data-max-num-cores-for-cluster-pitzer: 48,
          data-min-num-cores-for-cluster-owens: 1,
          data-max-num-cores-for-cluster-owens: 28,
        ]
  additional_constraints:
    widget: select
    options:
      - [
          "no constraints", "none",
        ]
      - [ 
          "40 core", "40core",
          data-min-num-cores-for-cluster-pitzer: 1,
          data-max-num-cores-for-cluster-pitzer: 40,
        ]
      - [ 
          "48 core", "40core", 
          data-min-num-cores-for-cluster-pitzer: 1,
          data-max-num-cores-for-cluster-pitzer: 48,
        ]
```
</details>

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203503722603241) by [Unito](https://www.unito.io)
