### ISSUE TITLE
help_bar should pull left

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2417]
the `help_bar` configuration creates dropdown menus that pull right (see below). These should pull left instead.

![image](https://user-images.githubusercontent.com/4874123/206543333-dc0a557c-0cf5-48c1-949f-cd663fd02e1f.png)

Here's the configuration to reproduce. 
```yaml
help_bar:
  - title: "Help"
    links:
      - title: "Doc Links"
      - title: "how to docs"
        icon_uri: fa://desktop
        url: "/docs"
        new_tab: false
      - title: "submit a help ticket"
        icon_uri: fa://question-circle
        url: "/tickets"
        new_tab: false
      - apps: "sys/bc_osc_rstudio_server"
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203518360052562) by [Unito](https://www.unito.io)
