### ISSUE TITLE
Custom Pages links for navigation

### ISSUE THREAD

**Issue by abujeda** [OSC/ondemand#2472]
Currently, to add a custom page (feature described in issue: https://github.com/OSC/ondemand/issues/2322) link to the navigation, we need to define a full custom navigation. custom navigation support custom page links.

Similar to `profiles`, it would be convenient to support adding custom page links to `help` menu.

Proposal:
New UserConfiguration property: page_links

Sample configuration, consistent with NavBar.

```
page_links:
  - page: "documentation"
    title: "Site Documentation"
    icon_uri: "fas://book"
```

<img width="400" alt="Screenshot 2023-01-10 at 10 44 43" src="https://user-images.githubusercontent.com/17336210/211531031-f7e580af-c164-4cc5-b9ac-a5920b337c19.png">

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1203792853708860) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
There's something here, I had #1909.  I was looking to replace the environment variables in  https://osc.github.io/ood-documentation/latest/customization.html#add-urls-to-help-menu for something more generic, as you indicate, fully customizable.  I closed #1909 given folks can do this entirely now.

But there could be something to it. We have now `help_bar`, maybe a `help_menu` they can redefine that'll add stuff?

The question I have is how it fits into the users/admins mental model of how to configure stuff.  It could be a simpler helper along the lines of `nav_categories`. I.e., completely ignored if redefined but used if someone's trying to partially customize.

**Comment by adaybujeda** [comment]
With that in mind, I had this idea: A custom navigation that is merged with the default navigation.
This attached navigation  will not have any effects in other menus.

This is an example

```yaml
    attach_navbar:
      - title: "Clusters"
        links:
          - title: "Custom in IA"
            icon_uri: "fas://search"
            url: "/test/my/path"
          - group: "Servers"
          - title: "Custom Server"
            icon_uri: "fas://search"
            url: "/test/my/path"
          - group: "Titan"
          - title: "New Group"
            icon_uri: "fas://search"
            apps: "sys/sas"
      - title: "Help"
        links:
          - group: "Profiles"
          - title: "Default"
            profile: ""
            icon_uri: fas://user
          - title: "Team 1"
            profile: "team1"
          - title: "Team 2"
            profile: "team2"
```

**Comment by adaybujeda** [comment]
Created a draft PR implementing the idea above:
https://github.com/OSC/ondemand/pull/2484

**Comment by abujeda** [comment]
I think I have found a config that is a bit nicer:

```yaml
    navbar_partial:
      help:
        - group: "Profiles"
        - title: "Default"
          profile: ""
          icon_uri: fas://user
        - title: "Team 1"
          profile: "team1"
      development:
        - group: "MyDocs"
        - title: "User Docs"
          url: "https://mydomain.com/user-docs"
          icon_uri: fas://user
        - title: "Company Docs"
          url: "https://mydomain.com/user-docs"
```

What do you think @johrstrom ?

**Comment by abujeda** [comment]
> I see you're adding for `development` - is that a feature you're wanting to use or guessing others will want?

Not sure to be honest. We definitely want to add to the `help` menu.
I thought that adding 1 or 2 links to any of the navigation items would be useful. By using this config structure, we could extend the implementation to more menus like:
```yaml
    navbar_partial:
      clusters:
      interactive apps:
      help:
```
But happy to leave that for another day.
So, just for the help menu. Shall I just create a new property `help_menu`?
Or use the `navbar_partial` and only recognize `help`?

```yaml
    navbar_partial:
      help:

    help_menu:
```
