### ISSUE TITLE
hiding check boxes doesn't hide help labels

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2562]
From discourse - https://discourse.openondemand.org/t/hiding-a-form-field-with-dynamic-form-widgets/2473 - hiding check boxes doesn't hide help labels.

You can tell from inspecting the html that the help text is a sibling of the hidden check box, not a child.
![image](https://user-images.githubusercontent.com/4874123/218204348-5920fdbd-60a7-4096-a147-d9b56df0028c.png)

here's a form.yml to replicate.

<details>

```yaml
attributes:
  cluster:
    widget: select
    options:
      - kingspeak
      - [
          'frisco1',
          data-hide-bc-email-on-started: true,
          data-hide-bc-num-hours: true
        ]
  bc_num_hours:
    value: 1
    min: 1
    step: 1
    help: "Maximum wall time on notchpeak-shared-short is 8 hours, general nodes 72 hours, owner nodes 14 days."
  bc_email_on_started:
    help: "If you do not receive the email, check your [Profile](https://www.chpc.utah.edu/role/user/edit_profile.php) for correct address."

form:
  - cluster
  - bc_num_hours
  - bc_email_on_started
```

</details>

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1203949894687169) by [Unito](https://www.unito.io)
