### ISSUE TITLE
auto_scripts smart attribute

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2575]
The new job composer, for convienence is going to need an automatic smart attribute that can collect all the shell scripts in the project directory.

So, given this configuration:
```yaml
form:
  - auto_scripts
attributes:
  auto_scripts:
    project_directory: '/path/to/some/directory'
```

The resulting `smart_attribute` should then generate a list of options from `Dir.glob("#{project_directory}/*.{sh,bash}")`

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1203972087802915) by [Unito](https://www.unito.io)
