### ISSUE TITLE
add defaults to create new script

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2650]
When you create a new script, we should add some form defaults.

I'm thinking these 2 as a starting place. Note that `cluster` is a computed value.

```yaml
title: 'the title that was given'
cluster:
  - job_clusters.reject { |c| c.kubernetes? || c.linux_host? || c.systemd? }
form:
  - auto_accounts
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204155402507902) by [Unito](https://www.unito.io)
