### ISSUE TITLE
data-set directives don't work for nearly duplicate ids

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2686]
You can test this errant behavior with this `form.yml`.

There are a couple use cases there that don't work
* with both `data-set-cluster` and `data-set-cluster-fs` directives, neither fields seem to be updated correctly when you toggle choices in `toggle_thing`.
* commenting out `data-set-cluster` directives and it _does_ update, but updates the wrong field. What you'd expect when only `data-set-cluster-fs` directives are enabled, it would update the `cluster_fs` field. However, it updates the `cluster` field instead.

```yaml
form:
  - cluster
  - cluster_fs
  - toggle_thing

attributes:
   toggle_thing:
     widget: select
     options:
      - [
          'first_thing', 'first_thing',
          data-set-cluster: pitzer,
          data-set-cluster-fs: pitzer_filesystem,
        ]
      - [
          'second_thing', 'second_thing',
          data-set-cluster: owens,
          data-set-cluster-fs: owens_filesystem,
        ]
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1204228547659448) by [Unito](https://www.unito.io)
