### ISSUE TITLE
data-option-for seems completely broken

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2688]
`data-option-for` directives seem completely broken.  What I'm especially frustrated with is the fact that there are a bunch of tests for this functionality, so why the test cases still pass is beyond me.

* Given the form below

### expected behavior
When you choose `first_thing` from the `Toggle Thing` select options, `Astronomy 5678` should be hidden.

### expected behavior
When you choose `first_thing` from the `Toggle Thing` select options, nothing happens.

```yaml
form:
  - toggle_thing
  - classroom

attributes:
  toggle_thing:
    widget: select
    options:
      - [
          'first_thing', 'first_thing',
          data-option-for-classroom-astronomy-5678: false,
        ]
      - [
          'second_thing', 'second_thing',
        ]
  classroom:
    widget: select
    options:
      - [ 'Physics 1234', 'physics_1234' ]
      - ['Astronomy 5678', 'astronomy_5678']
      - ['Math 4435', 'math_4435']
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1204229905361556) by [Unito](https://www.unito.io)
