### ISSUE TITLE
Missing error partial for custom page widgets

### ISSUE THREAD

**Issue by robinkar** [OSC/ondemand#2715]
If an error occurs rendering a widget in custom dashboard pages in 3.0, it causes an internal server error as it is trying to find the partial for widget errors under the wrong path (`custom_pages` instead of `dashboard`).

```
#<ActionView::MissingTemplate: Missing partial custom_pages/_widget_error, application/_widget_error with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :md, :markdown, :jbuilder]}. Searched in:
  * "/var/www/ood/apps/sys/dashboard/app/views"
  * "/opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/2.1.0-1/gems/ood_appkit-2.1.1/app/views"
>
```

To reproduce, configure the custom pages feature with a missing widget or add `<%= raise "" %>` to the widget.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204308262781440) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Can you share the configuration you're trying to use?

**Comment by robinkar** [comment]
Here is an simplified configuration that shows the bug, using the latest dev container.
```
custom_pages:
  bug:
    rows:
      - columns:
        - width: 12
          widgets:
            - motd
            - grafana

dashboard_layout:
  rows:
    - columns:
      - width: 12
        widgets:
          - motd
          - grafana
```

Here `motd` is a widget that exists, and `grafana` one that does not exist. 
On the dashboard(`http://localhost:8080/pun/sys/dashboard/`) it looks like this:
![image](https://user-images.githubusercontent.com/61623634/229435417-2ae96810-9873-4b48-a0b6-5cd3f8d98b2a.png)

If you go to `http://localhost:8080/pun/sys/dashboard/custom/bug` the `motd` widget does not get rendered, you get this instead:
![image](https://user-images.githubusercontent.com/61623634/229435504-55e2e974-bfcd-4c51-a564-8ea18ab89a5e.png)
