### ISSUE TITLE
duplicate apps in interactive apps panel if duplicates exist in navbar

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2728]
I'm using this configuration for a `nav_bar`.

<details>

```yaml
nav_bar:
  - files
  - clusters
  - interactive apps
  - my interactive sessions
  - title: 'Custom Link Menu'
    links:
      - title: "Report a bug"
        icon: "fa://bug"
        url: "https://www.osc.edu/"
      - title: "See a Report"
        icon: "fa://chart-bar"
        url: "https://www.osc.edu/"
  - title: 'Popular Apps'
    icon: "fa://star"
    apps:
      - 'sys/bc_osc_matlab'
      - 'sys/bc_osc_jupyter*'
      - 'sys/bc_osc_rstudio*'
```

</details>

As you can see, matlab `jupyter*` and rstudio are listed in a new menu item along with `interactive apps`.  So there are effectively 2 navbar menu items for each of these apps. This is fine, this is what I expected. 

However, in the `interactive apps` panel in the `my interactive sessions` page, there are duplicates for these apps listed here as you can see in this image.

![image](https://user-images.githubusercontent.com/4874123/230161812-29e34126-6039-4b21-9a3a-ec902fe2b984.png)
