### ISSUE TITLE
support_ticket email.from & description don't seem to do anything

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2729]
I'm using this configuration below, and the description doesn't seem to be appearing as the default text in the form. What's more is that the `email.from` setting doesn't seem to do anything either, given that the email from field is required in the form.

```
support_ticket:
  description: |
    There is some issue with this application.
  email:
    from: "ondemand@osc.edu"
    to: "wiag@osc.edu"
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204342326389537) by [Unito](https://www.unito.io)
