### ISSUE TITLE
single app menu item instead of dropdown

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2774]
I'm trying to do something like this yaml below where I only want to show 1 app, not in a drop-down menu but just as a single navbar entry.  Doc's don't indicate that is possible like this.

```yaml
      - title: 'Jupyter'
        icon: "fa://star"
        apps: 'sys/jupyter'
```

I can do this to achieve what I'm looking for, but I'm wondering if it'd be easier to do with the configuration above. The admin (me) is only expecting 1 item to be returned, so maybe if there is only 1 single item in the list it may be more appropriate to add it simply as a link instead of in a dropdown menu.

```yaml
      - title: 'Jupyter'
        icon: "fa://star"
        url: '/pun/sys/dashboard/batch_connect/sys/jupyter/session_contexts/new'
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1204450551246400) by [Unito](https://www.unito.io)

**Comment by abujeda** [comment]
I think it is more intuitive for that configuration to be a menu item because of the `apps` item being plural.

We could easily add this config as an top level menu link:
```yaml
      - title: 'Jupyter'
        icon: "fa://star"
        app: 'sys/jupyter'
```

I think we discussed having `app` and `apps` when we started discussing the nav configuration, but discarded the idea.

**Comment by johrstrom** [comment]
> I think we discussed having app and apps when we started discussing the nav configuration, but discarded the idea.

I don't recall it, but believe you. In any case, I'd imagine this is a big use case - folks wanting to show say 1 or 2 apps and instead of menus, they're just links on the navbar.

I would guess that profiles built around a single app like Rstudio/Jupyter/MATLAB/etc are going to be popular (but that is a guess based on how we run classrooms now).

**Comment by abujeda** [comment]
Do you like the idea of using `app` singular to indicate app link instead of menu?

I thought as well that using `url: app://sys/jupyter` might be an option, but It looks a bit awkward.

**Comment by johrstrom** [comment]
> Do you like the idea of using app singular to indicate app link instead of menu?

Sure, but I would like to support `apps: one_single_app` as well.

**Comment by abujeda** [comment]
I see, ok.

Admins that want to use a menu with a single app can still use:
```
      - title: 'Jupyter'
        icon: "fa://star"
        links:
          - 'sys/jupyter'
```

There is no need for `app` then.

**Comment by johrstrom** [comment]
That's still a menu though.

**Comment by abujeda** [comment]
Thats is what I meant.
If/when we make this change, in order to make a menu with a single application item, the only option will be:
```yaml
      - title: 'Jupyter'
        icon: 'fa://star'
        links:
          - 'sys/jupyter'
 ```
Because this config will now display a link instead of a menu with a link:
```yaml
      - title: 'Jupyter'
        icon: "fa://star"
        apps: 'sys/jupyter'
```

**Comment by johrstrom** [comment]
> My initial worry was that making this change would remove the possibility of creating a menu with a single application. 

Yea my thinking was to remove this behavior. What's the benefit here of having a menu with just one item?  It's an extra click (or button press for keyboard users) to see the one single item.

**Comment by abujeda** [comment]
I think it will be useful to update:
```yaml
      - title: 'Jupyter'
        icon: "fa://star"
        apps: 'sys/jupyter'
```
To display an application link with the `title` and `icon` overridden when the token matches a single app.

But, we should allow admins to create a menu with a single app link if they require it.
So the config below will display the menu with a single app link:
```yaml
      - title: 'Jupyter'
        icon: 'fa://star'
        links:
          - 'sys/jupyter'
```
And this config will display a menu with a single app link with the title and icon overridden.
```yaml
      - title: 'Single App Menu'
        icon: 'fa://star'
        links:
          - title: 'Jupyter'
             icon: ''fas://star
             apps: 'sys/jupyter'
```

**Comment by johrstrom** [comment]
> But, we should allow admins to create a menu with a single app link if they require it.

IDK if I see value in having a menu for one item. Is there a UX thing I'm missing here?  Why would they _require_ that?

**Comment by abujeda** [comment]
I wouldn't know why it would be required and I don't think it is related to UX. I just think that we should allow the administrators make the decision, if they want a link or a menu with a single item.

**Comment by abujeda** [comment]
Created a draft PR to implement the feature to override title and icon on app links.
This have the side effect of making the following config into a link instead of a menu:

```yaml
      - title: 'Jupyter'
        icon: 'fa://star'
        apps: 'sys/jupyter'
```

https://github.com/OSC/ondemand/pull/2804
