### ISSUE TITLE
Recently Used Apps Widget - Show display parameters if configured

### ISSUE THREAD

**Issue by abujeda** [OSC/ondemand#2781]
Based on the feedback from Tips And Tricks, it would be nice to show some information regarding the parameters that the recently used app will be launched with.

Currently, batch connect application attributes support the display property. If configured, this property will show the attribute with its value in the session panel. We could use this configuration to show these attribute values for the recently used apps in a `popover` effect.

```yaml
#rdesktop/form.yml
cluster: "dev-cluster"
attributes:
  bc_num_slots:
    display: true
  bc_num_hours:
    display: true
```

<img width="644" alt="Screenshot 2023-04-25 at 16 27 45" src="https://user-images.githubusercontent.com/17336210/234326835-9ffbca53-a64b-4022-9ecc-6d9f63043f85.png">
