### ISSUE TITLE
This app is missing information required to establish a connection.

### ISSUE THREAD

**Issue by zhan4429** [OSC/ondemand#2794]
I want to build a new OOD app for the nf-core pipeline (https://nf-co.re). The OOD app is just designed to use the convenient web portal to submit slurm jobs. As a result, there is no GUI, no server like Jupyer, and I do not need to use VNC. Below is my `submit.yml.erb`:

```
batch_connect:
  template: "basic"
script:
  accounting_id: <%= queue.blank? ? "null" : queue.strip %>
  wall_time: <%= ((walltime.blank? ? 1.0 : walltime.to_f) * 3600).to_i %>
  email: <%= ENV["USER"] %>@purdue.edu
  job_name: "OnDemand/nf-core"
  native:
    - "--nodes=1"
    - "--ntasks-per-node=1"
    - "--cpus-per-task=<%= num_cores.to_s %>"
    - "--gpus-per-node=<%= num_gpus.to_s %>"
```
After I launch the job, everything is running smoothly, expect that I can see this error message `This app is missing information required to establish a connection. Please contact support if you see this message.`. I am wondering how to get rid of this error message. 

![Screenshot 2023-05-02 at 8 35 52 PM](https://user-images.githubusercontent.com/90942318/235813483-c859518a-0a9e-41fe-9e65-6bbf6e9ee570.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1204519298892543) by [Unito](https://www.unito.io)
