### ISSUE TITLE
Auto scripts has extra `-` in `yaml` file

### ISSUE THREAD

**Issue by Oglopf** [OSC/ondemand#2864]
While working #2824 I noticed that when the `yaml` writes, there is a syntax error under `auto_scripts` that looks like the following:
```yaml
---
title: test1
form:
...
- auto_scripts
attributes:
  ...
  auto_scripts:
    options:
    - - hello_world.sh
      - "/users/PZS0714/travert/ondemand/misc/ondemand/apps/dashboard/data/projects/1/hello_world.sh"
```
There are 2 `- -` before the first `options` entry. This was happening before any changes were made to the `SmartAttributes` so it has likely been there but somehow has not bubbled up.

This is a ticket to figure out why that extra `-` is writing.

**Comment by johrstrom** [comment]
That's an array of arrays.

So that's equivalent to this, what we generally write by hand:

```yaml
  auto_scripts:
    options:
    - [ 
       hello_world.sh,
       "/users/PZS0714/travert/ondemand/misc/ondemand/apps/dashboard/data/projects/1/hello_world.sh"
      ]
```
