### ISSUE TITLE
Interactive apps menu / navbar customization automatic app groups

### ISSUE THREAD

**Issue by robinkar** [OSC/ondemand#3014]
Right now there there seems to be a lot of duplication needed when customizing the app menu how we want, especially with many profiles needing mostly the same configuration. For our uses, it would be nice if the groups were added automatically for the apps.
What we have:
```yml
interactive_apps_menu:
  title: "Apps"
  links:
    - group: "Editors"
    - apps:
      - type: sys
        subcategory: "Editors"
    - group: "Graphical applications"
    - apps:
      - type: sys
        subcategory: "Graphical applications"
    - group: "Servers"
    - apps:
      - type: sys
        subcategory: "Servers"
    - group: "Tools"
    - apps:
      - type: sys
        subcategory: "Tools"
    - group: "Course environments"
    - apps:
      - type: sys
        subcategory: "Course environments"
```

What we would like:
```yml
interactive_apps_menu:
  title: "Apps"
  links:
    - apps: # Probably need something here to tell it to add groups
      - type: sys
        subcategory: "Editors" # We may want to do some additional filtering based on metadata here
      - type: sys
        subcategory: "Graphical applications"
      - type: sys
        subcategory: "Servers"
      - type: sys
        subcategory: "Tools"
      - type: sys
        subcategory: "Course environments"
```
