### ISSUE TITLE
Interactive apps menu customization filter out Passenger apps

### ISSUE THREAD

**Issue by robinkar** [OSC/ondemand#3015]
I'm might have missed some part of the documentation that makes this possible right now, but there doesn't seem to be an easy way to filter out Passenger apps in the interactive app menu / navbar menu customization.

Right now we have an app category called Tools, which includes both Passenger apps (login node shell and other utils), and interactive apps (e.g. persistent compute node shell). In the navbar we would like to show these together as one group (category), while in the interactive apps menu we would like to show only the interactive apps.

This is somewhat related to #3014, as a configuration like this does not make much sense currently. With a configuration like the one below, the interactive apps menu includes also Passenger apps. Filtering by something like `role: batch_connect` could be expected to work as that is defined in the manifest.yml, but it does not work. I suppose metadata could be used here, but seems unnecessary to explicitly define whether apps are interactive or Passenger apps there.
```yml
interactive_apps_menu:
  title: "Apps"
  links:
    - apps:
      - type: sys # this could be just too "sys/*"
      # In the real config we'd have some category/subcategory/metadata filters here
```
