### ISSUE TITLE
data-set- support for checking and un-checking checkboxes

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#3182]
This feature is basically to allow for select options to have `data-set` directives that can check and uncheck a checkbox.

For support for something like so:

```yaml

cluster:
  - pitzer
  - owens

form:
  - checkbox_test
  - option_selector

attributes:
  option_selector:
    widget: select
    options:
      - [
          'check', 'check',
          data-set-checkbox-test: '1'
        ]
      - [
          'un-check', 'un-check',
          data-set-checkbox-test: '0'
        ]
  checkbox_test:
    widget: check_box
```
