### ISSUE TITLE
data-option-for should toggle the other field too

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#3242]
Consider the form in the details section below. This single `data-option-for` directive is effectively saying `large classroom size is an invalid option for the Geology classroom`

Changing the `classroom` works as expected. When `Geology` is chosen - `large` is hidden from the select options.

However, the inverse of that does not work as expected (or at least how I'd expect it). I.e., choosing a `large` classroom_size **does not** disable the `Geology` classroom.

To get the form into that state can only happen through changing the `classroom`. 

Changing the `classroom_size` to `large` should also disable the `Geology` option in `classroom`. 

<details>

```yaml
---
cluster:
  - "owens"
  - "pitzer"
attributes:
  classroom:
    widget: select
    options:
      - 'Physics'
      - 'Geology'
  classroom_size:
    widget: select
    options:
      - 'small'
      - 'medium'
      - ['large', 'large', data-option-for-classroom-geology: false,]
form:
  - classroom
  - classroom_size
```

</details>

**Comment by johrstrom** [comment]
It should be noted that when you have chosen `Physics` and `large` then choose `Geology` - the classroom_size field automatically changes from `large` to `small`.

Which is to say, this may not be needed because the end result puts the form into the correct state. 

I guess it's a question of which is worse/which is more unexpected? Both of these behaviors could be unexpected.

1. Hide `Geology` when `large` is chosen (what this ticket proposes to do).
2. change the select of `large` to something else (`small` in this case) when the classroom changes.

**Comment by Bubballoo3** [comment]
As discussed in #5453, this idea has the potential to lock forms in particular sets of options without it being obvious from the form itself. Consider the form
```
form: 
  - node_type
  - memory
attributes:
  node_type:
    widget: select
    options:
      - ['Advanced']
      - ['Basic']
  memory:
    widget: select
    options:
      - ['High', data-option-for-node-type-basic: false]
      - ['Medium', data-option-for-node-type-advanced: false]
 ```

The directives make sense and look innocent, but if the option-for directives were bidirectional the form would be stuck on the node type option (and its associated option-for) with no way to change it. With #5681, anybody who would like to have bidirectional behavior can simply define the directive on the other option as well.
