### ISSUE TITLE
_slurm_rpc_submit_batch_job: Invalid account or account/partition combination specified

### ISSUE THREAD

**Issue by gcpmendez** [OSC/ondemand#3253]
I receive the following message from the onDemand application:

![image](https://github.com/OSC/ondemand/assets/10725162/db540305-1154-48ab-87c2-5b85fbc2e14c)

From the VM where I installed onDemand I can launch jobs to that partition and with the same user without problems, that's why I'm surprised about this error.

This is my basic cluster configuration
```
---
v2:
  metadata:
    title: "teide"
  login:
    host: "10.5.22.100"
  job:
    adapter: "slurm"
    bin: "/usr/bin"
    conf: "/etc/slurm/slurm.conf"
```
Any suggestions where I could have the error?

thanks in advance.
