### ISSUE TITLE
Dynamic form JS data-option-for hide by default

### ISSUE THREAD

**Issue by robinkar** [OSC/ondemand#3345]
It would be nice to have the possibility of having all options in a select widget hidden by default, and explicitly show them only for specific options in other select widgets using `data-option-for`.

In other words, what I have (somewhat made up scenario, but not too far from reality):
```
gpu_type:
  widget: "select"
  options:
    - ["A100", "a100", data-option-for-slurm-partition-gpu: false, data-option-for-slurm-partition-gputest: false, data-option-for-slurm-partition-gpusmall: false, data-option-for-slurm-partition-gpumedium: false]
    - ["A100 MIG", "a100mig", data-option-for-slurm-partition-visualization: false, data-option-for-slurm-partition-gpu: false, data-option-for-slurm-partition-gpusmall: false, data-option-for-slurm-partition-gpumedium: false]
    - ["MI250", "mi250", data-option-for-visualization: false, data-option-for-slurm-partition-gputest: false]
```

What I want:
```
gpu_type:
  widget: "select"
  options:
    - ["A100", "a100", data-option-for-slurm-partition-visualization: true]
    - ["A100 MIG", "a100mig", data-option-for-slurm-partition-gputest: true]
    - ["MI250", "mi250", data-option-for-slurm-partition-gpu: true, data-option-for-slurm-partition-gpusmall: true, data-option-for-slurm-partition-gpumedium: true]
```

This would make it significantly easier to tell which options are available for each of the `slurm_partition` select options in some scenarios like the above without trying to figure out exactly what options are missing from the list.
