### ISSUE TITLE
Dynamic form JS data-show

### ISSUE THREAD

**Issue by robinkar** [OSC/ondemand#3346]
The data-hide option in forms is quite inconvenient if you have some widget that only is available for a small number of options.
Something that would work the opposite of `data-hide` would be nice to have, e.g. `data-show` or maybe `data-hide: false`.

So rather than having forms like this:
```
slurm_partition:
  widget: "select"
  options:
    - ["interactive", "interactive", data-hide-gpu-type: true]
    - ["small", "small", data-hide-gpu-type: true]
    - ["largemem", "largemem", data-hide-gpu-type: true]
    - ["test", "test", data-hide-gpu-type: true]
    - ["medium", "medium", data-hide-gpu-type: true]
    - ["longrun", "longrun", data-hide-gpu-type: true]
    - ["gpu", "gpu"]
```

I would want to have this:
```
slurm_partition:
  widget: "select"
  options:
    - ["interactive", "interactive"]
    - ["small", "small"]
    - ["largemem", "largemem"]
    - ["test", "test"]
    - ["medium", "medium"]
    - ["longrun", "longrun"]
    - ["gpu", "gpu", data-show-gpu-type: true]
```

Where the `gpu_type` select widget would be hidden by default, and shown only for the `gpu` partition.

**Comment by robinkar** [comment]
The GPU type field here would be a dropdown, while I think the `hidden_field` is always a textbox (unless there is a way to make it a dropdown I have missed).

This would also be useful beyond this case with GPUs, for example with reservations where some reservation might not be available for some account (i.e. hide reservation field for some account), and some reservations have the partition defined (i.e. hide the partition field for some reservation).

**Comment by johrstrom** [comment]
OK I made #3348 for auto reservations.

I'm not really sure how to implement this given everything is shown by default. I'd guess we'd need to collect all the data attributes and determine if there's only 1 state it _can_ be shown in and react off of that.

But auto_gpus and auto_reservations may make the whole thing moot.

**Comment by robinkar** [comment]
I think it could be fine to have some attribute be set for the GPU type field to toggle the behaviour, although some automatic detection would of course be better.
So something like:
```
gpu_type:
  widget: "select"
  hide_by_default: true
  options:
    - a100
    - mi250
```
I'm not sure how useful an auto_reservation or auto_gpus field would be for us, as right now as we are not using the auto_ attributes (mostly due to some missing features).
