### ISSUE TITLE
Path selector broken

### ISSUE THREAD

**Issue by Oglopf** [OSC/ondemand#3367]
We had a discourse come in after the `3.1` release about the path selector:
https://discourse.openondemand.org/t/label-is-not-displayed-when-using-path-selector/3281

Upon trying to answer or recreate it was discovered the current docs for this feature don't see to work if you follow them.

Using `3.1` and creating a `form.yml` with the following:
```yml
  working_dir:
    label: "Select Directory"
    widget: "path_selector"
    directory: "/path/to/my/home" # obfuscating, not actual text used
    show_hidden: true
    show_files: false
```
This results in a pop up that cannot be interacted with.

If you leave out the `directory` as the user does in the discourse sometimes the pop-up shows up, sometimes nothing happens. But again, even if the pop-up shows up I cannot interact with it.

**Comment by johrstrom** [comment]
> This results in a pop up that cannot be interacted with.

> If you leave out the directory as the user does in the discourse sometimes the pop-up shows up, sometimes nothing happens. But again, even if the pop-up shows up I cannot interact with it.

I can't replicate this behavior.

**Comment by genericdata** [comment]
I'm experiencing the same inability to interact with the "path_selector." The screen is greyed due to this HTML element, `<div class="modal-backdrop fade show"></div>`.  If I inspect and delete the element, I can interact with the path selector window. 

I can also tab through the options and type into the text box once reached through tab.

Simple form entry of:
```
  data_folder:
    widget: "path_selector"
    show_hidden: false
    show_files: false
```

Running on RHEL9.3 with ondemand 3.1.1.
