### ISSUE TITLE
Support common dynamic form patterns with just data attributes

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#337]
Two common patterns

1. a dropdown where when the selection changes the visibility of another field set of form elements
2. a dropdown where when the selection changes constraints on an input change (so the range of cores changes based on node type or cluster selection, for example)

More examples can be found by looking at our use of form.js.

**Comment by ericfranz** [comment]
As an example, see the descriptions of form.js in the MATLAB tutorial https://github.com/OSC/ood-documentation/pull/214 or our use of form.js or mentions of it in Discourse.

**Comment by ericfranz** [comment]
An example. https://github.com/OSC/bc_osc_ansys_workbench/blob/4e59abee1fb6896ab3dc7c7ba4307dd8a6c97f09/form.js has this JS for controlling visibility of these form inputs defined in the form.yml:

```yaml
  user_license_provider:
    widget: select
    label: "License provider"
    help: "Some users are required to provide their own license information"
    options:
      - ["I can use the OSC license", "osc"]
      - ["I need to use an external license", "external"]
  extern_license_server:
    label: "External License Server"
    placeholder: port@ip
  extern_license_file:
    label: "External License File"
    placeholder: port@ip
```

And corresponding form.js:

```js

function toggle_license_field_visibility() {
  let user_license_provider = $("#batch_connect_session_context_user_license_provider");

  toggle_visibilty_of_form_group(
    '#batch_connect_session_context_extern_license_server',
    user_license_provider.val() === 'external'
  );
  toggle_visibilty_of_form_group(
    '#batch_connect_session_context_extern_license_file',
    user_license_provider.val() === 'external'
  );
}

function set_user_license_provider_change_handler() {
  let user_license_provider = $("#batch_connect_session_context_user_license_provider");
  user_license_provider.change(toggle_license_field_visibility);
}

set_user_license_provider_change_handler();
```

Imagine instead no JavaScript is necessary instead all that we need is:

```diff
  user_license_provider:
    widget: select
    label: "License provider"
    help: "Some users are required to provide their own license information"
    options:
      - ["I can use the OSC license", "osc"]
-     - ["I need to use an external license", "external"]
+     - ["I need to use an external license", "external", data-scope-show: "external_licenses"]
  extern_license_server:
    label: "External License Server"
    placeholder: port@ip
+   data-scope: "external_licenses"
  extern_license_file:
    label: "External License File"
    placeholder: port@ip
+   data-scope: "external_licenses"
```
