### ISSUE TITLE
data-hide not picking up on names with capital letters

### ISSUE THREAD

**Issue by HazelGrant** [OSC/ondemand#3381]
To reproduce, create a test app with the following `form.yml` file:

```
form:
  - abc
  - def
  - Test
attributes:
  Test:
    widget: 'select'
    options: [
      ["abc", data-hide-def: true],
      ["def", data-hide-abc: true]
    ]
```

This will hide attribute def when abc is selected and vice versa. But if one of those is capitalized:

```
form:
  - abc
  - DEF
  - Test
attributes:
  Test:
    widget: 'select'
    options: [
      ["abc", data-hide-DEF: true],
      ["def", data-hide-abc: true]
```
The data-hide directive fails and attribute DEF does not disappear.
