### ISSUE TITLE
data-hide does not hide the button for path_selector

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#3425]
initially reported on discourse - https://discourse.openondemand.org/t/cluster-specific-modules-dont-populate-in-form-yml-erb/3287/20

I haven't replicated yet, but I'm sure it's real.

**Comment by HazelGrant** [comment]
Can reproduce with this form.yml:

```
form:
  - dir1
  - dir2
  - hide
attributes:
  hide:
    widget: 'select'
    options: 
      - ['hide dir1', 'hide dir1', data-hide-dir1: true]
      - ['hide dir2', 'hide dir2', data-hide-dir2: true]
  dir1:
    widget: "path_selector"
  dir2:
    widget: "path_selector"
```

**Comment by johrstrom** [comment]
> Can reproduce with this form.yml:

It's the `Select Path` button that we also need to hide. I just tried with that form and could reproduce. The text input is hidden, but not the button to `Select Path`.

**Comment by HazelGrant** [comment]
There's more to this. `data-hide-*` fails for `radio_button` and `file_attachments` as well.

```
form:
  - dir1
  - dir2
  - hide
  - radio_test
  - hide_radio
  - attachments_test
  - hide_attachments
attributes:
  hide:
    widget: 'select'
    options: 
      - ['hide dir1', 'hide dir1', data-hide-dir1: true]
      - ['hide dir2', 'hide dir2', data-hide-dir2: true]
  dir1:
    widget: "path_selector"
  dir2:
    widget: "path_selector"
  radio_test:
    widget: "radio_button"
    value: "1"
    options:
      - ["one", 1]
      - ["zero", 0]
  hide_radio:
    widget: "select"
    options:
      - [ 'show radio', 'show radio']
      - [ 'hide radio', 'hide radio', data-hide-radio-test: true]
  attachments_test:
    widget: "file_attachments"
  hide_attachments:
    widget: "select"
    options:
      - ["show attachments", "show attachments"]
      - ["hide attachments", "hide attachments", data-hide-attachments-test: true]
  ```

https://github.com/OSC/ondemand/assets/6969170/f1253e47-658c-4bf5-96f5-a16769db7217
