### ISSUE TITLE
data-hide does not work on radio buttons

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#3506]
From discourse, with the given YAML below, one cannot hide the `jupyter` widget regardless of the `show_details` selection. The discourse user notes that if `jupyter` is a `select` widget this works.

<details>

```yaml
form:
  - show_details
  - jupyter
attributes:
  show_details:
    widget: check_box
    label: "Show details"
    html_options:
      data:
        hide-jupyter-when-unchecked: true
  jupyter:
    widget: radio_button
    label: "Jupyter"
    options:
      - ["Jupyter Lab", "0"]
      - ["Jupyter Notebook", "1"]
```

</details>
