### ISSUE TITLE
Not able to use 'filter' in batch connect forms

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#3604]
Looks like #605 is back in another spot. From discourse - https://discourse.openondemand.org/t/the-variable-name-filter-is-not-cached/3542

It comes from this line where we're using `to_json` on the session context directly instead of casting that to say open struct before casting back to json.

https://github.com/OSC/ondemand/blob/114c0359da4241e945e50172936a2a0510af188c/apps/dashboard/app/controllers/batch_connect/session_contexts_controller.rb#L46

Steps to replicate:
* You can use this form below
* Select B and submit the form.

```yaml
form:
  - filter
attributes:
  filter:
    widget: select
    options:
    - ["A"]
    - ["B"]
```

Expected behavior:
* `B` is cached and is currently selected when you reload the page.
* The key and value `filter: 'B'` is serialized correctly to the cache file.

Actual behaviour:
* `A` is selected when you reload the page.
* Something really funky is serialized to the cache file.
