### ISSUE TITLE
update_ood_portal creates OIDC settings though there's no OIDC in ood-portal.yml

### ISSUE THREAD

**Issue by aw-huit** [OSC/ondemand#3831]
Hello:

Here's the relevant part of my /etc/ood/config/ood_portal.yml: 
```
ssl:
  - 'SSLCertificateFile "/etc/ssl/private/cert.crt"'
  - 'SSLCertificateKeyFile "/etc/ssl/private/private_key.key"'
dex_uri: /dex
dex:
    ssl: true
    connectors:
        - type: ldap
          id: ldap
          name: LDAP
          config:
            host: hostname
            insecureSkipVerify: false
            insecureNoSSL: false
            bindDN: something
            bindPW: notpassword
            userSearch:
              baseDN: dc=one,dc=two
              filter: "(objectClass=three)"
              username: x
              idAttr: y
              emailAttr: z
              nameAttr: 1
              preferredUsernameAttr: 2
host_regex: '[^/]+'
node_uri: '/node'
rnode_uri: '/rnode'
user_map_cmd: '/etc/ood/add_user.sh'
```

Here's the relevant section of /etc/httpd/conf.d/ood-portal.conf

```
SetEnv OOD_PUN_URI "/pun"
  <Location "/pun">
    AuthType openid-connect
    Require valid-user


    ProxyPreserveHost On
    ProxyAddHeaders On
    ProxyPassReverse "http://localhost/pun"
```

Why is it setting /pun to openid-connect?
