### ISSUE TITLE
radio_button simple array doesn't work

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#3871]
Consider the form below.  Both of these have select options that are defined as an array of scalars (an array of strings).

However, only one works (the select widget leftright).

```yaml
form:
  - updown
  - leftright
attributes:
  updown:
    widget: 'radio_button'
    options:
      - up 
      - down
  leftright:
    widget: 'select'
    options:
      - left
      - right
```

The `radio_button` fails with this error complaining about the fact that we're trying to access the second field of the array for the label.

![image](https://github.com/user-attachments/assets/0b0ae08a-36bb-4977-883d-ebc3cf3062b0)
