### ISSUE TITLE
Use Dex for simple authentication option?

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#393]
See https://github.com/dexidp/dex

- once compiled, it is a single Go binary
- it accepts one argument when launching which is the config file

When building OnDemand, we could build an optional rpm ondemand-dex. We could extend the ood-portal-generator to generate config for this server as well.

I do not know anything else about the project however. Of course another alternative is CILogon or Globus Auth as the default auth, though there is still the problem of how to handle mapping, and some sites don't have CILogon end points.

**Comment by treydock** [comment]
Not finding many alternatives except this one: https://github.com/ory/hydra, but appears like it doesn't provide a login page which it clearly states in README.  This would not help us as a replacement for Basic Auth. I am investigating Dex as it seems like it may be good default option for OnDemand authentication.

**Comment by treydock** [comment]
I got Dex working with very little changes to Apache configs. Just had to change the OIDC discovery URL. I verified this on webdev02.  How should the ood-portal-generator handle the configs? There are many connectors support like Google, GitHub and LDAP. Setting up ports and such makes sense but I worry about trying to handle all possible options for LDAP. Maybe just have `dex_connectors` key and let people setup their own connector.

Running service:
```
cd /root/go/src/github.com/dexidp/dex
./bin/dex serve ./config.yaml &
```

Config used without comments:

```
issuer: https://ondemand-dev.osc.edu:5554/dex

storage:
  type: sqlite3
  config:
    file: examples/dex.db

web:
  http: 0.0.0.0:5556
  https: 0.0.0.0:5554
  tlsCert: /etc/pki/tls/certs/ondemand-dev.osc.edu.crt
  tlsKey: /etc/pki/tls/private/ondemand-dev.osc.edu.key

telemetry:
  http: 0.0.0.0:5558

oauth2:
    skipApprovalScreen: true

staticClients:
- id: ondemand-dev.osc.edu
  redirectURIs:
  - 'https://ondemand-dev.osc.edu/oidc'
  name: 'OnDemand'
  secret: <OMIT>

connectors:
- type: ldap
  id: ldap
  name: LDAP
  config:
    host: ldap1.<OMIT DOMAIN>:636
    bindDN: cn=read,ou=Admin,<OMIT BASEDN>
    bindPW: <OMIT>
    userSearch:
      baseDN: ou=People,<OMIT BASEDN>
      filter: "(objectClass=oscUser)"
      username: uid
      idAttr: uid
      emailAttr: mail
      nameAttr: gecos
      preferredUsernameAttr: uid
    groupSearch:
      baseDN: ou=Groups,<OMIT BASEDN>
      filter: "(objectClass=oscGroup)"
      userMatchers:
      - userAttr: dn
        groupAttr: member
      nameAttr: cn

enablePasswordDB: false
```

**Comment by treydock** [comment]
Pull request for code changes: #474 

Pull request for packaging changes: https://github.com/OSC/ondemand-packaging/pull/85

**Comment by johrstrom** [comment]
I guess I have to dissent here and ask, are we sure folks would use this given you now have to configure odic _and_ ldap.? If the target is basic auth users, would they really want the this? What's the benefit of using dex + ldap when you could just use ldap directly.

I guess I would ask, are we really giving users more options or just more complexity. Especially given all the help docs we already have around authentication, basic auth is the one we don't actually get support questions for.

**Comment by treydock** [comment]
The way I set this up is they don't have to setup oidc, it's done automatically if dex is enabled.  They would only have to setup LDAP via dex.  The default process is no-config using Dex with embedded username/password so it's 0 config install to get working authentication. To switch dex to LDAP requires just providing the Dex LDAP configs which is no more complicated than providing Apache options for LDAP.

I would hope few sites are using basic auth in production which might be why we get so few support questions.

There is a lot of extra logic added so that if Dex is used it will auto generate the OIDC configs, but they can be overridden if desired but working defaults are used so literally the only thing a site must configure is LDAP.

**Comment by treydock** [comment]
This is all a site would have to add (ideally) to ensure dex is using LDAP. THings like whether to use SSL and which hostname to use are all pulled from the existing `ood_portal.yml` config values to avoid additional configuration requirements.

```yaml
dex_connectors:
- type: ldap
  id: ldap
  name: LDAP
  config:
    host: ldap1.<OMIT DOMAIN>:636
    bindDN: cn=read,ou=Admin,<OMIT BASEDN>
    bindPW: <OMIT>
    userSearch:
      baseDN: ou=People,<OMIT BASEDN>
      filter: "(objectClass=oscUser)"
      username: uid
      idAttr: uid
      emailAttr: mail
      nameAttr: gecos
      preferredUsernameAttr: uid
    groupSearch:
      baseDN: ou=Groups,<OMIT BASEDN>
      filter: "(objectClass=oscGroup)"
      userMatchers:
      - userAttr: DN
        groupAttr: member
      nameAttr: cn
```
