### ISSUE TITLE
how to globally set custom bc_num_hours item

### ISSUE THREAD

**Issue by smoors** [OSC/ondemand#4132]
i'm testing the global form item documented at https://osc.github.io/ood-documentation/latest/how-tos/app-development/interactive/form.html#global-batch-connect-form-items

i've set the following items in global_bc_items.yml:

```yml
  global_num_cores:
    widget: "number_field"
    label: "Number of cores"
    value: 1
    required: true
    min: 1
    max: 64
    step: 1
  global_bc_num_hours:
    label: "Number of hours"
    widget: "number_field"
    value: 12
    min: 1
    max: 120
    step: 1
```

for `num_cores` everything works as intended after replacing every `num_cores` string with `global_num_cores`.

however, for the built-in `bc_num_hours` item, i cannot replace the strings because they are of course built in. prefixing with `global_` seems to have the effect that it is no longer a built-in item, and thus the customizations are ignored.

how can this be fixed?
