### ISSUE TITLE
App/Sub-app attribute label change doesnt always apply

### ISSUE THREAD

**Issue by adamboutcher** [OSC/ondemand#4162]
If you use a * in the cluster field to provide a drodown menu of the available clusters to the user, then the attribute to change that field label doesn't apply and only shows the default label of cluster.

```
---
title: "My Application"
cluster: "*cluster*"
attributes:
  cluster:
    display: true
    label: "Host"
```
