### ISSUE TITLE
Sub App override of category and sub-category doesnt apply

### ISSUE THREAD

**Issue by adamboutcher** [OSC/ondemand#4171]
Not sure if this would be a bug depending on how the logic runs but if you try to override the category/subcategory of a sub-app, this isn't reflected in the WebUI.

**Comment by adamboutcher** [comment]
I'll close the issue if its intended behaviour and I'm just trying to do something freaky.

**Comment by johrstrom** [comment]
🤦‍♂ Actually, you may be able to supply the subcategory in the form.yml

https://github.com/OSC/ondemand/blob/419d230aecd36bd6bac54a776cdd36ed3b3f6428/apps/dashboard/app/models/batch_connect/app.rb#L129

```yaml
form:
# ...
attributes:
# ...
subcategory: 'some other subcategory'
```
