### ISSUE TITLE
dynamic batch connect support for changing the help text

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#4253]
This may be a duplicate of an issue out there already but I can't find it at the moment.

In any case, the idea for this ticket is to change the `help` text given different options. Consider these options with these `data-help` (or maybe a `data-help-message` not sure about the exact directive name) attributes. The premise here is to update the `help` text field of the `node_type` widget when a given option is selected.

```
  node_type:
    widget: select
    options:
      - [ 'small',  'small',  data-help: 'Small machines have 10 cores and 100 GB of RAM'  ]
      - [ 'medium', 'medium', data-help: 'Medium machines have 50 cores and 500 GB of RAM'  ]
      - [ 'large',  'large',  data-help: 'Large machines have 100 cores and 1 TB of RAM' ]
```
