### ISSUE TITLE
screen readers don't read labels for radio buttons in bc forms

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#4289]
screen readers don't read labels for radio buttons in bc forms. I think this is because the label is `for` a different ID.

Consider this YAML. the options for 'whole' and 'shared' are read because they have their own label, but the base label 'gpu' is missed entirely.

```yaml
form:
  - gpu
attributes:
  gpu:
    widget: radio_button
    options:
      - ['shared', 'shared']
      - ['whole', 'whole']
    value: 'shared'
    required: true
    help: |
      Request a shared GPU or use the whole GPU.
```
