### ISSUE TITLE
`path_selector` widget wording should be more general

### ISSUE THREAD

**Issue by simonLeary42** [OSC/ondemand#4398]
The top of the `path_selector` popup window says "Select Your Working Directory", but I'm not using it for a working directory, I'm using it to select the path to a container image file. It seems like I should be able to customize this header in my `form.yml`.

https://github.com/OSC/ondemand/blob/5acdc363e534f35422af86bfc98f8ae2ee9d8888/apps/dashboard/app/views/shared/_path_selector_table.html.erb#L21

**Comment by genericdata** [comment]
What should the `path_selector` attribute be called?  I have a pull request #4426 here that I believe would do it with the option named `popup_title`. It allows you to set the popup title or it will just use the widget name. 


This will display "Container" within the popup
```
  Container:
    widget: "path_selector"
    show_hidden: true
    show_files: true
```

This will display "Select the container"
```
  Container:
    widget: "path_selector"
    show_hidden: true
    show_files: true
    popup_title: "Select the container"
```
