### ISSUE TITLE
Add Kubernetes as a backend

### ISSUE THREAD

**Issue by KristinaPlazonic** [OSC/ondemand#447]
We are using OnDemand for teaching computational science classes (using Slurm scheduler). These classes use Jupyter notebooks and RStudio, but usually these interactive jobs don't require a lot of resources. We could conserve resources by packing several Jupyter notebooks on the same cores/memory. So it would be really useful for scaling instructional infrastructure if we could launch jupyter notebooks and RStudio on Kubernetes (RStudio already launches as a container!) instead of Slurm. For example, JupyterHub is deployable on Kubernetes already. 

Thanks for your consideration!

**Comment by ahkumar** [comment]
See a lot of value in this.

**Comment by elgalu** [comment]
That's great news @johrstrom ! Perhaps sharing a K8s example project is enough for some of us to start trying it out and not having to wait for the full documentation.

**Comment by johrstrom** [comment]
OK yea, may as well get this party started!  I hope this helps.  And indeed, I'll respond through this ticket if you have any more questions. As it is new, it would be a good idea to start getting 2nd opinions.

Here's a simple description of what we have here:  We deploy pods (a single container pod) into the users namespace. Every user has their own namespace and we assume you've got that all locked down with the right policies (pod security policies are being deprecated - so, we use Kyverno). A user of UID 1500 & GID 1501 will always start a container with those IDs. You can add supplemental groups automatically (below) - but you'll always force users to run containers as themselves - We set it up this way so I don't believe there's a way around it.


Here's a yaml for the cluster definition. Things of note 
* `username_prefix` - this is the username in your ~/.kube/config so one user doesn't collide with another (test and production and so on).
* `namespace_prefix` - all users get their own namespace, and this is the optional prefix for that namespace. We have kyverno policies to be sure they match that regular expression `test-.+`.
* auth is how you indent to authenticate. We use OIDC, so it has some assumptions about how OnDemand will use `--context`. I think another setting is `managed` where the ~/.kubeconfig is managed entirely outside of OnDemand and we don't pass/use or set a `--context`, we just assume it's set already.

```yaml
---
v2:
  metadata:
    title: "Kubernetes"
    hidden: true
  job:
    adapter: "kubernetes"
    cluster: "ood-test"
    bin: "/usr/local/bin/kubectl"
    username_prefix: "test-"
    namespace_prefix: "user-"
    all_namespaces: false
    auto_supplemental_groups: true
    server:
      endpoint: "https://your.k8s.host.edu"
      cert_authority_file: "/some/cert/file/kubernetes-ca.crt"
    auth:
      type: "oidc"
  batch_connect:
    ssh_allow: false
```

For OIDC we provide some shell script hooks to run before the PUN starts up to setup a users ~/.kube/config. 

https://github.com/OSC/ondemand/tree/master/hooks

We use `pun_pre_hook_root_cmd` and `pun_pre_hook_exports` (another undocumented feature) to run these hooks. (One thing of note here, as you may see in the hooks - if you pass an environment variable `OIDC_FOO` you need to access in the hook scripts as `OOD_OIDC_FOO`)

https://github.com/OSC/ondemand/blob/a0891c597bdf56ed7bcc22b5a5f7a0702e33445e/ood-portal-generator/share/ood_portal_example.yml#L258-L271

We've updated our jupyter app to use kubernetes, though we're treating the container much more like the regular Slurm infrastructure in that it's a base image and we mount all sorts of stuff to get SSSD and the module system to work. So, nothing is _really_ inside the container - it just looks like our base OS so that we can use host mounted files.

https://github.com/osc/bc_osc_jupyter
