### ISSUE TITLE
Apps with Infinite Time

### ISSUE THREAD

**Issue by SpontaneousDuck** [OSC/ondemand#561]
I am attempting to write and app for my system and would like the user to be able to request an indefinite length job. My SLURM cluster is set up to allow this and I am able to create jobs form the command line with no time limit. The documentation states that I should be able to override any defaults for any form value (`bc_num_hours` in my case). I have modified the `form.yml` for my app and added the below lines:
```
bc_num_hours:
    label: "Number of Hours"
    value: 24
    required: false
```
This does not override the required flag though and still requires me to enter something. Am I doing this correctly?

**Comment by johrstrom** [comment]
Hi! I don't believe we handle this out of the box, so you'll probably need to do some fancy footwork in the `submit.yml.erb`.  You'll probably also need to specify a new field for hours.

Something like this may work for you.
```yml
form:
  - hours
attributes:
  hours:
    widget: "number_field"
    min: 0
    value: 24
    label: "Number of Hours"
    help: "Set to 0 for unlimited"
```

Assuming `-t UNLIMITED` is the correct way to submit for unlimited time limit, your `submit.yml.erb` would look like this.
```erb
<%-
   time_limit = hours == 0 ? "UNLIMITED" : ('00:%02d:00' % hours)
-%>
---
script:
  native:
    - "-t"
    - "<%= time_limit %>"
```

OR if unlimited time limits is the default if you don't specify any time it would look like this.
```erb
---
script:
  native:
  <%- if hours != 0 -%>
    - "-t"
    - "<%= '00:%02d:00' % hours %>"
  <%- end -%>
```
I'm unfamilar with how to get unlimited time limits through `sbatch` so I've given you both. Let me know if that's the command for it looks like and I'll confirm.
