### ISSUE TITLE
Option data attributes are not showing up in radio button widgets

### ISSUE THREAD

**Issue by KinanAlAttar** [OSC/ondemand#575]
When setting up a radio widget with data attributes for showing/hiding certain form groups in form.yml for a bc app, for example,

```
    widget: radio
    label: "ANSYS Workbench version"
    help: "This defines the version of ANSYS you want to load."
    options:
      - [ "2020R1", "ansys/2020R1", data-ood-show-scope: "tutorial" ]
      - [ "2019R2", "ansys/2019R2" ]
      - [ "2019R1", "ansys/2019R1", data-ood-show-scope: "tutorial" ]
      - [ "19.2",   "ansys/19.2"   ]
      - [ "19.1",   "ansys/19.1"   ]
      - [ "18.1",   "ansys/18.1"   ]
      - [ "17.2",   "ansys/17.2"   ]
```

The data attributes fail to show up when the form is displayed. The file that deals with creating the widget is the following,

```
dashboard/app/helpers/batch_connect/session_contexts_helper.rb
```

Here are a couple of links that can be useful in fixing this bug,
https://edgeapi.rubyonrails.org/classes/ActionView/Helpers/FormOptionsHelper.html#method-i-collection_radio_buttons
https://github.com/bootstrap-ruby/bootstrap_form

Both links provide information about the helper method (collection_radio_buttons) that is being used in creating the widget. Currently, the helper method does not support blocks.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737582433104) by [Unito](https://www.unito.io)
