### ISSUE TITLE
Make dashboard widgets configurable

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#707]
https://trello.com/c/KF6qJ3yv/70-make-dashboard-widgets-configurable

1. enable adding new widgets as a single erb file to /etc/ood/config/apps/dashboard/views/widgets/
2. enable changing the default layout of the widgets
3. move existing widgets to the views/widgets directory of the dashboard app
4. ability to configure how often this view will get reloaded vs cache used (by default reload on every request)

The default layout will be what we have now at ondemand.osc.edu, so if motd is present (two columns)

1. MOTD widget on left (col-md-8)
2. XDMoD widgets on right (col-md-4)

If the motd is not present, widgets take advantage of the space: (two columns)

1. XDMoD efficiency reports left (col-md-4)
2. XDMoD job widgets on right (col-md-8)

**Comment by ericfranz** [comment]
Here is a simple way to enable configuring the layout: a list of widgets and whether or not those widgets should have fixed widths or can expand to fill available space.

```yaml
widgets:
  - name: motd_widget
    width: 8
  - name: xdmod_widget_job_efficiency
    width: 4
  - name: xdmod_widget_jobs
    width: 4
    maxwidth: 8
```

So a simple algorithm trying to maximize the space available will place the xdmod widgets on the right column.

**Comment by ericfranz** [comment]
Problem with above is it doesn't specify a column like col1 of 8 width and col2 of 4 width. So the current dashboard layout is impossible, which is col1 8 width with motd, col2 4 width with 2 xdmod widgets.

There is no good solution for auto-adjusting widgets to fill empty space if the motd is not available.

We want a default layout but want to enable sites to provide their own. It would be annoying if to add motd and xdmod widgets you had to enable them AND add a line to the widget layout.

So there are a lot of different use cases that a simple design like above doesn't cleanly address.

**Comment by ericfranz** [comment]
We could just start with this:

```
layout:
  - col:
    width: 8
    widgets:
      - name: motd_widget
  - col: 4
      - name: xdmod_widget_job_efficiency
      - name: xdmod_widget_jobs
```

- If the widget widths are not provided, the width is width of the column

And also support:


```
layout:
  - name: motd_widget
    width: 8
  - name: xdmod_widget_job_efficiency
    width: 4
  - name: xdmod_widget_jobs
    width: 4
```

- this assumes 1 column 12 width

And we could even support separate rows:


All three mapping to bootstrap layout directly.

```
layout:
  - row:
    - col:
      width: 8
      widgets:
        - name: motd_widget
  - row:
    - col: 4
        - name: xdmod_widget_job_efficiency
        - name: xdmod_widget_jobs
```

Finally, if a column has no widgets we would move all the widgets to the left to fill the empty space (so with the default layout being motd left, xdmod widgets right - so if no motd, xdmod widgets fill the space).

The two column layout above would let us reproduce we have now

**Comment by ericfranz** [comment]
Decided to go with:

```
layout:
  - row:
    - col:
      width: 8
      widgets:
        - name: motd_widget
  - row:
    - col: 4
        - name: xdmod_widget_job_efficiency
        - name: xdmod_widget_jobs
```

- If a column is empty, do we always shift all the widgets to the left
