### ISSUE TITLE
Support adding arbitrary Apache directives to sections of ood-portal.conf

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#708]
Be able to add arbitrary directives to the , perhaps as a multiline string:

```yaml
custom_directives_vhost: |
  # comment to include in headers
  TraceEnable off
  FileETag None
  Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains;"
custom_directives_locations: |
  Header set …
```

Or maybe we allow specifying the individual locations.

Also, if we are supporting a multiline string, it may also be nice to support the array of strings instead - and add that for the auth section that we ask users to add an array of strings. The multiline string is for sure more natural to write. Codewise, we would just detect if it were a string or an array - and if array, `join("\n")` to get the string

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737643475414) by [Unito](https://www.unito.io)

**Comment by treydock** [comment]
I think multiline strings are the wrong approach, we should just support array of lines.  Multiline strings for things like Puppet would be ugly to implement especially in Hiera. It's much cleaner to just support an array of lines like we already do for things like SSL directives and Auth directives, that's the pattern we've already adopted.

**Comment by treydock** [comment]
```yaml
custom_directives_vhost:
  - # comment to include in headers
  - TraceEnable off
  - FileETag None
  - Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains;"
custom_directives_locations:
  - Header set …
```

I do not think multiline strings work in Hiera which is used by Puppet to define data.  It's also more prone to errors and less straight forward than an array of lines.
