### ISSUE TITLE
form.cluster may not respet cachable flags

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#750]
From https://discourse.osc.edu/t/does-ood-v1-8-still-support-our-multiple-instance-setup/1226 it seems that if you have something similar to what's below, the app will not respect the cacheable setting and in fact use the the cached value which could be erroneous (the cluster doesn't exist or you don't have access to it).

```yaml
form:
  - cluster
attributes:
  cluster: 
    cacheable: false
```
