### ISSUE TITLE
dynamic batch connect apps

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#851]
I know we've talked about this, but I don't know if there's any ticket for the actual feature.  Looks like we worked on #513 but decided against it, though I'm not sure if we decided against the approach in the PR or the idea altogether.

We have a similar approach in our own BC apps, so maybe our jquery javascript approach may be mature enough.

I think the result could be something like setting for node types.

```yaml
    options:
      - [
          "any",     "any",
          data-min-ppn-for-cluster-owens: 1,
          data-max-ppn-for-cluster-owens: 28,
          data-min-ppn-for-cluster-pitzer: 1,
          data-max-ppn-for-cluster-pitzer: 48,
          data-option-for-cluster-owens: true,
          data-option-for-cluster-pitzer: true
        ]
```

`data-option-for-<ATTRIBUTE>-<ATTRIBUTE VALUE>`

* would register a handler and show/disable the given option or field when the attribute changed to the specific value. We do this now in our batch connect apps.

`data-[min,max]-<CORES ATTRIBUTE>-for-<CHANGE ATTRIBUTE>-<ATTRIBUTE VALUE>`

* would register a handler to change the mins and maxes of `CORES ATTRIBUTE` when `CHANGE ATTRIBUTE` is set to `CHANGE ATTRIBUTE VALUE`.

These are common patterns we see all the time, needing to hide something based off of a selected value and changing mins and maxes. Is this approach generic enough to pick up other use cases? maybe not, but maybe we don't need to worry about _every_ use case just yet. _This_ may provide a lot of value for folks. 

Here's what's complete and what's still to do.

* [x] #1447
* [x] #1431
* [x] #1432 
* [x] #1380 
* [x] #2115

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202815755532406/1202823247675256) by [Unito](https://www.unito.io)
