### ISSUE TITLE
How to add Shell app Targets

### ISSUE THREAD

**Issue by gagandaroach** [OSC/ondemand#861]
Hello. 

How may I add additional shortcuts in the navbar Cluster -> shell to log in submenu?

![image](https://user-images.githubusercontent.com/25407172/105773294-4a503380-5f29-11eb-8c47-9ed0313e0b80.png)

For example, in the above screenshot I would like to add 2 new ssh options against other nodes with specific options.

![image](https://user-images.githubusercontent.com/25407172/105773339-5b00a980-5f29-11eb-9d4c-0df3f245a6d0.png)
I have been able to add custom options to the file menu with the `/etc/ood/config/apps/dashboard/initializers/ood.rb`

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737594178340) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
The comment on this ticket may help. Essentially what you want to do is add a cluster file, but it's only got data for SSH. So you can't submit jobs to it, but it'll show up in the navbar there.

https://github.com/OSC/ondemand/issues/835#issuecomment-756303393

**Comment by gagandaroach** [comment]
![image](https://user-images.githubusercontent.com/25407172/106087138-fe4bed00-60e8-11eb-907a-68233d922e56.png)

Okay very nice, I was able to add a separate ssh login target as I was looking for.

```
[root@dh-ood clusters.d]# cat mgmt2.yml 
---
v2:
  metadata:
    title: "Management Node"
    url: "https://dh-mgmt2.hpc.msoe.edu"
    hidden: false
  login:
    host: "dh-mgmt2.hpc.msoe.edu"
```

**Question** Is it possible I could remove the "shell access" text from the link?
