### ISSUE TITLE
Cannot specify custom Dex theme

### ISSUE THREAD

**Issue by guimaluf** [OSC/ondemand#888]
my `ood_portal.yml` has the following entry:

```yaml
dex:
  issuer: https://myrul:5554
  connectors:
    ...
  frontend:
    theme: my-theme
    extra:
      loginButtonText: "Click here"
```

So far neither `issuer` and `theme` are catch by `update_ood_portal`

```bash 
/opt/ood/ood-portal-generator/sbin/update_ood_portal
No change in Apache config.
No change in the Dex config.
Completed successfully!
```
