### ISSUE TITLE
make matching apps based on metadata more flexible

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#937]
To match a pinned app from a configuration based off of the metadata fields we use direct equivalence. 

https://github.com/OSC/ondemand/blob/93fb3da91a062221b49db4736cd2ffa67d2bd810/apps/dashboard/app/apps/token_matcher.rb#L60-L64

So this ticket is to support a more flexible way to match against metadata than by simple equivalence. `File::FNM_EXTGLOB` has been suggested. 

So a config like this:
```yaml
# config file in ondemand.d/ directory
pinned_apps:
   - tags:  *magic*
```

Could match this app that has many tags.
```yaml
# some apps manifest.yml
title: some App
metadata:
   tags: magic sorcery occult
```
